import 'dart:convert';

import 'package:flutter_test/flutter_test.dart';

import '../../tool/sbom_lib.dart';

/// A miniature pubspec.lock in exactly the shape pub writes: two-space
/// indentation, quoted versions, an sdks section at the end.
const _lock = '''
# Generated by pub
# See https://dart.dev/tools/pub/glossary#lockfile
packages:
  archive:
    dependency: transitive
    description:
      name: archive
      sha256: a96e8b390886ee8abb49b7bd3ac8df6f451c621619f52a26e815fdcf568959ff
      url: "https://pub.dev"
    source: hosted
    version: "4.0.9"
  base32:
    dependency: "direct main"
    description:
      name: base32
      sha256: "3937ca6f0c02d1c0d1c8f0ba9a59f1cd8e5e3e7d9a5c3c5c5f5b5a5958575655"
      url: "https://pub.dev"
    source: hosted
    version: "2.1.3"
  flutter_lints:
    dependency: "direct dev"
    description:
      name: flutter_lints
      sha256: "1111111111111111111111111111111111111111111111111111111111111111"
      url: "https://pub.dev"
    source: hosted
    version: "6.0.0"
  flutter:
    dependency: "direct main"
    description: flutter
    source: sdk
    version: "0.0.0"
sdks:
  dart: ">=3.11.4 <4.0.0"
  flutter: ">=3.38.4"
''';

void main() {
  group('parseLockfile', () {
    test(
      'reads name, version, hash and dependency kind for a hosted package',
      () {
        final packages = parseLockfile(_lock);
        final archive = packages.firstWhere((p) => p.name == 'archive');

        expect(archive.version, '4.0.9');
        expect(
          archive.sha256,
          'a96e8b390886ee8abb49b7bd3ac8df6f451c621619f52a26e815fdcf568959ff',
        );
        expect(archive.source, 'hosted');
        expect(archive.isDevOnly, isFalse);
      },
    );

    test('strips the quotes pub puts around some values', () {
      final base32 = parseLockfile(_lock).firstWhere((p) => p.name == 'base32');

      expect(base32.version, '2.1.3');
      expect(base32.sha256, startsWith('3937ca6f'));
      expect(base32.sha256, isNot(contains('"')));
    });

    test('marks a direct dev dependency as dev-only, because it is not part '
        'of what ships', () {
      final lints = parseLockfile(
        _lock,
      ).firstWhere((p) => p.name == 'flutter_lints');

      expect(lints.isDevOnly, isTrue);
    });

    test('keeps an SDK package that has no hash', () {
      final flutter = parseLockfile(
        _lock,
      ).firstWhere((p) => p.name == 'flutter');

      expect(flutter.source, 'sdk');
      expect(flutter.sha256, isNull);
    });

    test('stops at the sdks section rather than reading it as a package', () {
      final names = parseLockfile(_lock).map((p) => p.name);

      expect(names, isNot(contains('dart')));
      expect(names, hasLength(4));
    });
  });

  group('buildCycloneDx', () {
    Map<String, dynamic> bom() =>
        jsonDecode(
              buildCycloneDx(
                packages: parseLockfile(_lock),
                appName: 'dula_auth',
                appVersion: '1.0.0',
                timestamp: DateTime.utc(2026, 1, 2, 3, 4, 5),
              ),
            )
            as Map<String, dynamic>;

    test('declares a CycloneDX 1.5 JSON document', () {
      final b = bom();

      expect(b['bomFormat'], 'CycloneDX');
      expect(b['specVersion'], '1.5');
      expect(b['version'], 1);
    });

    test('records the application itself as the subject', () {
      final component =
          (bom()['metadata'] as Map)['component'] as Map<String, dynamic>;

      expect(component['type'], 'application');
      expect(component['name'], 'dula_auth');
      expect(component['version'], '1.0.0');
    });

    test('uses a pub purl and carries the SHA-256 from the lockfile', () {
      final components = (bom()['components'] as List).cast<Map>();
      final archive = components.firstWhere((c) => c['name'] == 'archive');

      expect(archive['purl'], 'pkg:pub/archive@4.0.9');
      expect((archive['hashes'] as List).first, {
        'alg': 'SHA-256',
        'content':
            'a96e8b390886ee8abb49b7bd3ac8df6f451c621619f52a26e815fdcf568959ff',
      });
    });

    test('scopes dev-only dependencies as excluded, so a consumer can tell '
        'what actually ships from what only built it', () {
      final components = (bom()['components'] as List).cast<Map>();

      expect(
        components.firstWhere((c) => c['name'] == 'flutter_lints')['scope'],
        'excluded',
      );
      expect(
        components.firstWhere((c) => c['name'] == 'archive')['scope'],
        'required',
      );
    });

    test('omits the hashes field entirely when the lockfile has no hash', () {
      final components = (bom()['components'] as List).cast<Map>();
      final flutter = components.firstWhere((c) => c['name'] == 'flutter');

      expect(flutter.containsKey('hashes'), isFalse);
    });

    test(
      'is deterministic: the same lockfile yields byte-identical output',
      () {
        String once() => buildCycloneDx(
          packages: parseLockfile(_lock),
          appName: 'dula_auth',
          appVersion: '1.0.0',
          timestamp: DateTime.utc(2026, 1, 2, 3, 4, 5),
        );

        expect(once(), once());
      },
    );
  });
}
